
server:
  port: 8763
  tomcat:
    uri-encoding: UTF-8

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true   # 优先使用IP地址方式进行注册服务
    appname: ${spring.application.name}
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30

  server:
    enableSelfPreservation: false
    evictionIntervalTimerInMs: 4000

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka